// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpK2c6lvs2klO-L6PJHoMgUG7ZcPxOJik',
    appId: '1:375268473370:web:97110ffc646f3018392fa3',
    messagingSenderId: '375268473370',
    projectId: 'treecko-c8c52',
    authDomain: 'treecko-c8c52.firebaseapp.com',
    databaseURL: 'https://treecko-c8c52-default-rtdb.firebaseio.com',
    storageBucket: 'treecko-c8c52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfK3ZBn9Vs9fbvkobPx3IG1mRRHv_hU1E',
    appId: '1:375268473370:android:98c8afb087b36130392fa3',
    messagingSenderId: '375268473370',
    projectId: 'treecko-c8c52',
    databaseURL: 'https://treecko-c8c52-default-rtdb.firebaseio.com',
    storageBucket: 'treecko-c8c52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxSWKg5st6-HGNxmXw4ndhaT3yoC2Uvh0',
    appId: '1:375268473370:ios:2406d1228fa54a71392fa3',
    messagingSenderId: '375268473370',
    projectId: 'treecko-c8c52',
    databaseURL: 'https://treecko-c8c52-default-rtdb.firebaseio.com',
    storageBucket: 'treecko-c8c52.appspot.com',
    iosClientId: '375268473370-eddj5rva6ipu14auj49lsvr7euo20v52.apps.googleusercontent.com',
    iosBundleId: 'com.treecko.movil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxSWKg5st6-HGNxmXw4ndhaT3yoC2Uvh0',
    appId: '1:375268473370:ios:2406d1228fa54a71392fa3',
    messagingSenderId: '375268473370',
    projectId: 'treecko-c8c52',
    databaseURL: 'https://treecko-c8c52-default-rtdb.firebaseio.com',
    storageBucket: 'treecko-c8c52.appspot.com',
    iosClientId: '375268473370-eddj5rva6ipu14auj49lsvr7euo20v52.apps.googleusercontent.com',
    iosBundleId: 'com.treecko.movil',
  );
}
